from __future__ import annotations

IDIOMAS = (
    ("pt", "Português"),
    ("es", "Español"),
    ("en", "English"),
    ("fr", "Français"),
    ("ru", "Русский"),
    ("de", "Deutsch"),
    ("zh", "中文"),
    ("ko", "한국어"),
    ("ja", "日本語"),
    ("ar", "العربية"),
)

TRADUCOES = {
    "pt": {
        "app_title": "Palpite Milionário", "subtitle": "Gerador de combinações para estudo e entretenimento. Não realiza apostas nem movimenta dinheiro. Consulte os resultados oficiais em https://www.loteriasonline.caixa.gov.br.", "lotteries": "Loterias", "language": "Idioma", "history": "Histórico dos resultados anteriores", "refresh": "Atualizar resultados", "quantity": "Quantidade de jogos", "numbers": "Números por jogo", "profile": "Perfil estatístico", "verify": "Verificar atualizações", "special": "Especial", "generate": "Gerar palpites", "clear": "Limpar", "save": "Salvar palpites", "check": "Conferir resultado", "print": "Visualizar palpites para impressão", "version": "Versão", "mega": "Mega-Sena", "lotofacil": "Lotofácil", "quina": "Quina", "mais": "+Milionária", "lotomania": "Lotomania", "dupla": "Dupla Sena", "dia": "Dia de Sorte", "super": "SuperSete",
    },
    "es": {
        "app_title": "Palpite Millonario", "subtitle": "Generador de pronósticos para loterías brasileñas", "lotteries": "Loterías", "language": "Idioma", "history": "Historial de resultados anteriores", "refresh": "Actualizar resultados", "quantity": "Cantidad de juegos", "numbers": "Números por juego", "profile": "Perfil estadístico", "verify": "Buscar actualizaciones", "special": "Especial", "generate": "Generar pronósticos", "clear": "Limpiar", "save": "Guardar pronósticos", "check": "Comprobar resultado", "print": "Ver pronósticos para imprimir", "version": "Versión", "mega": "Mega-Sena", "lotofacil": "Lotofácil", "quina": "Quina", "mais": "+Millonaria", "lotomania": "Lotomania", "dupla": "Dupla Sena", "dia": "Día de la Suerte", "super": "Super Siete",
    },
    "en": {
        "app_title": "Millionaire Picks", "subtitle": "Combination generator for study and entertainment. It does not place bets or handle money. Check official results at https://www.loteriasonline.caixa.gov.br.", "lotteries": "Lotteries", "language": "Language", "history": "Previous results history", "refresh": "Update results", "quantity": "Number of games", "numbers": "Numbers per game", "profile": "Statistical profile", "verify": "Check for updates", "special": "Special", "generate": "Generate picks", "clear": "Clear", "save": "Save picks", "check": "Check result", "print": "View picks for printing", "version": "Version", "mega": "Mega-Sena", "lotofacil": "Lotofácil", "quina": "Quina", "mais": "+Million", "lotomania": "Lotomania", "dupla": "Dupla Sena", "dia": "Day of Luck", "super": "Super Seven",
    },
    "fr": {"app_title": "Pronos Millionnaire", "subtitle": "Générateur de pronostics pour les loteries brésiliennes", "lotteries": "Loteries", "language": "Langue", "history": "Historique des résultats précédents", "refresh": "Actualiser les résultats", "quantity": "Nombre de jeux", "numbers": "Numéros par jeu", "profile": "Profil statistique", "verify": "Rechercher des mises à jour", "special": "Spécial", "generate": "Générer des pronostics", "clear": "Effacer", "save": "Enregistrer les pronostics", "check": "Vérifier le résultat", "print": "Voir les pronostics à imprimer", "version": "Version", "mega": "Mega-Sena", "lotofacil": "Lotofácil", "quina": "Quina", "mais": "+Millionnaire", "lotomania": "Lotomania", "dupla": "Dupla Sena", "dia": "Jour de Chance", "super": "Super Sept"},
    "ru": {"app_title": "Миллионные прогнозы", "subtitle": "Генератор прогнозов для бразильских лотерей", "lotteries": "Лотереи", "language": "Язык", "history": "История прошлых результатов", "refresh": "Обновить результаты", "quantity": "Количество игр", "numbers": "Чисел в игре", "profile": "Статистический профиль", "verify": "Проверить обновления", "special": "Специальные", "generate": "Создать прогнозы", "clear": "Очистить", "save": "Сохранить прогнозы", "check": "Проверить результат", "print": "Просмотреть прогнозы для печати", "version": "Версия", "mega": "Mega-Sena", "lotofacil": "Lotofácil", "quina": "Quina", "mais": "+Миллионер", "lotomania": "Lotomania", "dupla": "Dupla Sena", "dia": "День удачи", "super": "Супер семь"},
    "de": {"app_title": "Millionen-Tipps", "subtitle": "Tippgenerator für brasilianische Lotterien", "lotteries": "Lotterien", "language": "Sprache", "history": "Verlauf früherer Ergebnisse", "refresh": "Ergebnisse aktualisieren", "quantity": "Anzahl der Spiele", "numbers": "Zahlen pro Spiel", "profile": "Statistisches Profil", "verify": "Nach Updates suchen", "special": "Spezial", "generate": "Tipps erzeugen", "clear": "Leeren", "save": "Tipps speichern", "check": "Ergebnis prüfen", "print": "Tipps zum Drucken anzeigen", "version": "Version", "mega": "Mega-Sena", "lotofacil": "Lotofácil", "quina": "Quina", "mais": "+Millionär", "lotomania": "Lotomania", "dupla": "Dupla Sena", "dia": "Glückstag", "super": "Super Sieben"},
    "zh": {"app_title": "百万选号", "subtitle": "巴西彩票选号器", "lotteries": "彩票", "language": "语言", "history": "历史开奖结果", "refresh": "更新结果", "quantity": "游戏数量", "numbers": "每局号码", "profile": "统计配置", "verify": "检查更新", "special": "特别号码", "generate": "生成选号", "clear": "清除", "save": "保存选号", "check": "核对结果", "print": "查看打印选号", "version": "版本", "mega": "Mega-Sena", "lotofacil": "Lotofácil", "quina": "Quina", "mais": "+百万", "lotomania": "Lotomania", "dupla": "Dupla Sena", "dia": "幸运日", "super": "超级七"},
    "ko": {"app_title": "백만장자 번호", "subtitle": "브라질 복권 번호 생성기", "lotteries": "복권", "language": "언어", "history": "이전 결과 기록", "refresh": "결과 업데이트", "quantity": "게임 수", "numbers": "게임당 번호", "profile": "통계 프로필", "verify": "업데이트 확인", "special": "특별 번호", "generate": "번호 생성", "clear": "지우기", "save": "번호 저장", "check": "결과 확인", "print": "인쇄용 번호 보기", "version": "버전", "mega": "Mega-Sena", "lotofacil": "Lotofácil", "quina": "Quina", "mais": "+백만", "lotomania": "Lotomania", "dupla": "Dupla Sena", "dia": "행운의 날", "super": "슈퍼 세븐"},
    "ja": {"app_title": "ミリオネア予想", "subtitle": "ブラジル宝くじの予想番号ジェネレーター", "lotteries": "宝くじ", "language": "言語", "history": "過去の結果履歴", "refresh": "結果を更新", "quantity": "ゲーム数", "numbers": "1ゲームの数字", "profile": "統計プロフィール", "verify": "更新を確認", "special": "特別番号", "generate": "予想を生成", "clear": "クリア", "save": "予想を保存", "check": "結果を確認", "print": "印刷用の予想を表示", "version": "バージョン", "mega": "Mega-Sena", "lotofacil": "Lotofácil", "quina": "Quina", "mais": "+ミリオネア", "lotomania": "Lotomania", "dupla": "Dupla Sena", "dia": "幸運の日", "super": "スーパーセブン"},
    "ar": {"app_title": "اختيارات المليونير", "subtitle": "مولّد اختيارات لليانصيب البرازيلي", "lotteries": "اليانصيب", "language": "اللغة", "history": "سجل النتائج السابقة", "refresh": "تحديث النتائج", "quantity": "عدد الألعاب", "numbers": "الأرقام في كل لعبة", "profile": "الملف الإحصائي", "verify": "التحقق من التحديثات", "special": "خاص", "generate": "إنشاء الاختيارات", "clear": "مسح", "save": "حفظ الاختيارات", "check": "التحقق من النتيجة", "print": "عرض الاختيارات للطباعة", "version": "الإصدار", "mega": "Mega-Sena", "lotofacil": "Lotofácil", "quina": "Quina", "mais": "+المليون", "lotomania": "Lotomania", "dupla": "Dupla Sena", "dia": "يوم الحظ", "super": "سبعة خارقة"},
}

_DINAMICOS = {
    "pt": {"waiting_prize": "Próximo prêmio: aguardando atualização oficial...", "estimated": "Próximo prêmio estimado", "next_contest": "Próximo concurso", "last_contest": "Último concurso", "drawn": "dezenas sorteadas", "price_waiting": "Valor de referência: aguardando configuração...", "price_game": "Referência por combinação", "total": "Referência total", "games_generated": "jogo(s) gerado(s) para", "click_generate": "Clique em 'Gerar palpites' para criar combinações para estudo e entretenimento com base no histórico oficial.", "version": "Versão", "trevos": "Trevos", "numbers_column": "Núm. por coluna"},
    "es": {"waiting_prize": "Próximo premio: esperando actualización oficial...", "estimated": "Próximo premio estimado", "next_contest": "Próximo concurso", "last_contest": "Último concurso", "drawn": "números sorteados", "price_waiting": "Precio de la apuesta: esperando configuración...", "price_game": "Precio por juego", "total": "Total", "games_generated": "juego(s) generado(s) para", "click_generate": "Haz clic en 'Generar pronósticos' para crear juegos con base en el historial oficial.", "version": "Versión", "trevos": "Tréboles", "numbers_column": "Núm. por columna"},
    "en": {"waiting_prize": "Next prize: waiting for official update...", "estimated": "Estimated next prize", "next_contest": "Next draw", "last_contest": "Last draw", "drawn": "drawn numbers", "price_waiting": "Reference value: waiting for configuration...", "price_game": "Reference per combination", "total": "Reference total", "games_generated": "game(s) generated for", "click_generate": "Click 'Generate picks' to create combinations for study and entertainment based on official history.", "version": "Version", "trevos": "Clovers", "numbers_column": "Numbers per column"},
    "fr": {"waiting_prize": "Prochain gain : en attente de la mise à jour officielle...", "estimated": "Prochain gain estimé", "next_contest": "Prochain tirage", "last_contest": "Dernier tirage", "drawn": "numéros tirés", "price_waiting": "Prix du jeu : en attente de configuration...", "price_game": "Prix par jeu", "total": "Total", "games_generated": "jeu(x) généré(s) pour", "click_generate": "Cliquez sur « Générer des pronostics » pour créer des jeux selon l'historique officiel.", "version": "Version", "trevos": "Trèfles", "numbers_column": "Numéros par colonne"},
    "ru": {"waiting_prize": "Следующий приз: ожидание официального обновления...", "estimated": "Ожидаемый следующий приз", "next_contest": "Следующий тираж", "last_contest": "Последний тираж", "drawn": "выпавшие числа", "price_waiting": "Цена ставки: ожидание настройки...", "price_game": "Цена игры", "total": "Итого", "games_generated": "игр создано для", "click_generate": "Нажмите «Создать прогнозы», чтобы создать игры на основе официальной истории.", "version": "Версия", "trevos": "Клеверы", "numbers_column": "Чисел в столбце"},
    "de": {"waiting_prize": "Nächster Gewinn: offizielles Update wird erwartet...", "estimated": "Geschätzter nächster Gewinn", "next_contest": "Nächste Ziehung", "last_contest": "Letzte Ziehung", "drawn": "gezogene Zahlen", "price_waiting": "Spieleinsatz: Konfiguration wird erwartet...", "price_game": "Preis pro Spiel", "total": "Gesamt", "games_generated": "Spiel(e) erzeugt für", "click_generate": "Klicken Sie auf „Tipps erzeugen“, um Spiele anhand des offiziellen Verlaufs zu erstellen.", "version": "Version", "trevos": "Kleeblätter", "numbers_column": "Zahlen pro Spalte"},
    "zh": {"waiting_prize": "下一奖项：等待官方更新……", "estimated": "预计下一奖项", "next_contest": "下一期开奖", "last_contest": "上期开奖", "drawn": "开奖号码", "price_waiting": "投注价格：等待配置……", "price_game": "每局价格", "total": "总计", "games_generated": "为其生成的游戏", "click_generate": "点击“生成选号”，根据官方历史记录创建游戏。", "version": "版本", "trevos": "幸运草", "numbers_column": "每列号码"},
    "ko": {"waiting_prize": "다음 당첨금: 공식 업데이트 대기 중...", "estimated": "예상 다음 당첨금", "next_contest": "다음 추첨", "last_contest": "지난 추첨", "drawn": "추첨 번호", "price_waiting": "베팅 가격: 설정 대기 중...", "price_game": "게임당 가격", "total": "합계", "games_generated": "생성된 게임", "click_generate": "공식 기록을 바탕으로 게임을 만들려면 ‘번호 생성’을 클릭하세요.", "version": "버전", "trevos": "클로버", "numbers_column": "열당 번호"},
    "ja": {"waiting_prize": "次回賞金：公式更新を待っています…", "estimated": "次回予想賞金", "next_contest": "次回抽選", "last_contest": "前回抽選", "drawn": "抽選数字", "price_waiting": "購入価格：設定を待っています…", "price_game": "1ゲームの価格", "total": "合計", "games_generated": "生成されたゲーム", "click_generate": "公式履歴に基づいてゲームを作成するには「予想を生成」をクリックしてください。", "version": "バージョン", "trevos": "クローバー", "numbers_column": "列ごとの数字"},
    "ar": {"waiting_prize": "الجائزة التالية: في انتظار التحديث الرسمي...", "estimated": "الجائزة التالية المتوقعة", "next_contest": "السحب التالي", "last_contest": "السحب الأخير", "drawn": "الأرقام المسحوبة", "price_waiting": "سعر الرهان: في انتظار الإعداد...", "price_game": "سعر اللعبة", "total": "الإجمالي", "games_generated": "لعبة تم إنشاؤها لـ", "click_generate": "انقر على «إنشاء الاختيارات» لإنشاء ألعاب استناداً إلى السجل الرسمي.", "version": "الإصدار", "trevos": "نباتات البرسيم", "numbers_column": "الأرقام لكل عمود"},
}
for _idioma, _textos in _DINAMICOS.items():
    TRADUCOES[_idioma].update(_textos)

_PERFIS = {
    "pt": {"conservador": "Conservador", "equilibrado": "Equilibrado", "agressivo": "Agressivo", "fechamento": "Fechamento"},
    "es": {"conservador": "Conservador", "equilibrado": "Equilibrado", "agressivo": "Agresivo", "fechamento": "Cobertura"},
    "en": {"conservador": "Conservative", "equilibrado": "Balanced", "agressivo": "Aggressive", "fechamento": "Coverage"},
    "fr": {"conservador": "Conservateur", "equilibrado": "Équilibré", "agressivo": "Agressif", "fechamento": "Couverture"},
    "ru": {"conservador": "Консервативный", "equilibrado": "Сбалансированный", "agressivo": "Агрессивный", "fechamento": "Покрытие"},
    "de": {"conservador": "Konservativ", "equilibrado": "Ausgeglichen", "agressivo": "Aggressiv", "fechamento": "Abdeckung"},
    "zh": {"conservador": "保守", "equilibrado": "均衡", "agressivo": "激进", "fechamento": "覆盖"},
    "ko": {"conservador": "보수적", "equilibrado": "균형", "agressivo": "공격적", "fechamento": "조합 커버리지"},
    "ja": {"conservador": "保守", "equilibrado": "バランス", "agressivo": "積極的", "fechamento": "カバレッジ"},
    "ar": {"conservador": "محافظ", "equilibrado": "متوازن", "agressivo": "جريء", "fechamento": "تغطية"},
}
for _idioma, _perfis in _PERFIS.items():
    for _chave, _texto in _perfis.items():
        TRADUCOES[_idioma][f"profile_{_chave}"] = _texto


def traduzir(idioma: str, chave: str, fallback: str = "") -> str:
    return TRADUCOES.get(idioma, TRADUCOES["pt"]).get(chave, TRADUCOES["pt"].get(chave, fallback))
